name: Release

on:
  push:
    tags:
      - 'v*'

env:
  LLVM_VERSION: 14.0.6
  LLVM_VERSION_MAJOR: 14
  PKG_TARGET: null
  EXECUTABLE: null

jobs:
  build:
    strategy:
      matrix:
        os:
        - ubuntu-22.04
        - macos-12
        # - windows-2022
        node: [18]

    runs-on: ${{ matrix.os }}

    steps:

    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}

    - name: Install on Linux
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        echo "PKG_TARGET=node${{ matrix.node }}-linux-x64" >> "$GITHUB_ENV"
        echo "EXECUTABLE=joelang-${{ github.ref_name }}-x64-linux" >> "$GITHUB_ENV"

    - name: Install on macOS
      if: startsWith(matrix.os, 'macos')
      run: |
        echo "PKG_TARGET=node${{ matrix.node }}-macos-x64" >> "$GITHUB_ENV"
        echo "EXECUTABLE=joelang-${{ github.ref_name }}-x64-macos" >> "$GITHUB_ENV"

    - name: Install on Windows
      if: startsWith(matrix.os, 'windows')
      run: |
        echo "PKG_TARGET=node${{ matrix.node }}-win-x64" >> "$GITHUB_ENV"
        echo "EXECUTABLE=joelang-${{ github.ref_name }}-x64-win" >> "$GITHUB_ENV"

    # Install all dependencies
    - name: Install dependencies
      run: |
        npm install
        npm install -g pkg

    # Build the project
    - name: Build project
      run: npm run build

    # Build executables for different platforms and archs
    - name: Build executables
      run: |
        pkg -t ${{ env.PKG_TARGET }} --output "${{ env.EXECUTABLE }}" _build/compile.js && chmod +x ${{ env.EXECUTABLE }}

    - uses: actions/upload-artifact@v3
      with:
        name: joelang-${{ github.ref_name }}-x64-${{ matrix.os }}
        path: ${{ env.EXECUTABLE }}
        if-no-files-found: error

  release:
    needs: build

    runs-on: ubuntu-latest

    steps:

    # Download the artifacts
    - uses: actions/download-artifact@v3

    # Create the release
    - name: Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        draft: false
        prerelease: true
        files: joelang-artifact-${{ github.ref_name }}-node*-*/joelang-${{ github.ref_name }}-node*-*-*
        name: Release ${{ github.ref_name }}
