name: Test Joelang Compiler

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        # - ubuntu-latest
        - windows-latest
        # - macOS-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1.8.0

    # - name: Install LLVM and GCC (Ubuntu)
    #   if: runner.os == 'Linux'
    #   run: |
    #     wget https://apt.llvm.org/llvm.sh
    #     sudo chmod +x llvm.sh
    #     sudo ./llvm.sh 15 all
    #     sudo apt-get update
    #     # sudo apt-get install -y llvm clang gcc
    #     sudo apt-get install -y cmake zlib1g-dev

    # - name: Install LLVM and GCC (macOS)
    #   if: runner.os == 'macOS'
    #   run: |
    #     brew install cmake llvm@15
    #     brew install gcc

    # - name: Install LLVM and GCC (Windows)
    #   if: runner.os == 'Windows'
    #   run: |
    #     # choco install llvm --version=15.0.7
    #     # choco install mingw
    #     llvm-config --cmakedir
    #     npm config set cmake_LLVM_DIR C:\Users\dev\llvm-13.0.1.src\build\lib\cmake\llvm

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run build

    - name: Test executable
      run: |
        # Your test commands go here, for example:
        npx jest -- e2e.spec.js
